/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database;


import de.uke.iam.parkinson_on_fhir.database.tables.Assessments;
import de.uke.iam.parkinson_on_fhir.database.tables.Bodyparts;
import de.uke.iam.parkinson_on_fhir.database.tables.Devices;
import de.uke.iam.parkinson_on_fhir.database.tables.Measurements;
import de.uke.iam.parkinson_on_fhir.database.tables.Ratings;
import de.uke.iam.parkinson_on_fhir.database.tables.Sensors;
import de.uke.iam.parkinson_on_fhir.database.tables.Sources;
import de.uke.iam.parkinson_on_fhir.database.tables.Subjects;
import de.uke.iam.parkinson_on_fhir.database.tables.Tasks;
import de.uke.iam.parkinson_on_fhir.database.tables.Tasktypes;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 376223918;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.assessments</code>.
     */
    public final Assessments ASSESSMENTS = Assessments.ASSESSMENTS;

    /**
     * The table <code>public.bodyparts</code>.
     */
    public final Bodyparts BODYPARTS = Bodyparts.BODYPARTS;

    /**
     * The table <code>public.devices</code>.
     */
    public final Devices DEVICES = Devices.DEVICES;

    /**
     * The table <code>public.measurements</code>.
     */
    public final Measurements MEASUREMENTS = Measurements.MEASUREMENTS;

    /**
     * The table <code>public.ratings</code>.
     */
    public final Ratings RATINGS = Ratings.RATINGS;

    /**
     * The table <code>public.sensors</code>.
     */
    public final Sensors SENSORS = Sensors.SENSORS;

    /**
     * The table <code>public.sources</code>.
     */
    public final Sources SOURCES = Sources.SOURCES;

    /**
     * The table <code>public.subjects</code>.
     */
    public final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.tasktypes</code>.
     */
    public final Tasktypes TASKTYPES = Tasktypes.TASKTYPES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Assessments.ASSESSMENTS,
            Bodyparts.BODYPARTS,
            Devices.DEVICES,
            Measurements.MEASUREMENTS,
            Ratings.RATINGS,
            Sensors.SENSORS,
            Sources.SOURCES,
            Subjects.SUBJECTS,
            Tasks.TASKS,
            Tasktypes.TASKTYPES);
    }
}
