/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database;


import de.uke.iam.parkinson_on_fhir.database.tables.Assessments;
import de.uke.iam.parkinson_on_fhir.database.tables.Bodyparts;
import de.uke.iam.parkinson_on_fhir.database.tables.Devices;
import de.uke.iam.parkinson_on_fhir.database.tables.Measurements;
import de.uke.iam.parkinson_on_fhir.database.tables.Ratings;
import de.uke.iam.parkinson_on_fhir.database.tables.Sensors;
import de.uke.iam.parkinson_on_fhir.database.tables.Sources;
import de.uke.iam.parkinson_on_fhir.database.tables.Subjects;
import de.uke.iam.parkinson_on_fhir.database.tables.Tasks;
import de.uke.iam.parkinson_on_fhir.database.tables.Tasktypes;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.assessments</code>.
     */
    public static final Assessments ASSESSMENTS = Assessments.ASSESSMENTS;

    /**
     * The table <code>public.bodyparts</code>.
     */
    public static final Bodyparts BODYPARTS = Bodyparts.BODYPARTS;

    /**
     * The table <code>public.devices</code>.
     */
    public static final Devices DEVICES = Devices.DEVICES;

    /**
     * The table <code>public.measurements</code>.
     */
    public static final Measurements MEASUREMENTS = Measurements.MEASUREMENTS;

    /**
     * The table <code>public.ratings</code>.
     */
    public static final Ratings RATINGS = Ratings.RATINGS;

    /**
     * The table <code>public.sensors</code>.
     */
    public static final Sensors SENSORS = Sensors.SENSORS;

    /**
     * The table <code>public.sources</code>.
     */
    public static final Sources SOURCES = Sources.SOURCES;

    /**
     * The table <code>public.subjects</code>.
     */
    public static final Subjects SUBJECTS = Subjects.SUBJECTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = Tasks.TASKS;

    /**
     * The table <code>public.tasktypes</code>.
     */
    public static final Tasktypes TASKTYPES = Tasktypes.TASKTYPES;
}
