/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database.tables;


import de.uke.iam.parkinson_on_fhir.database.Keys;
import de.uke.iam.parkinson_on_fhir.database.Public;
import de.uke.iam.parkinson_on_fhir.database.tables.records.BodypartsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bodyparts extends TableImpl<BodypartsRecord> {

    private static final long serialVersionUID = 185154062;

    /**
     * The reference instance of <code>public.bodyparts</code>
     */
    public static final Bodyparts BODYPARTS = new Bodyparts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BodypartsRecord> getRecordType() {
        return BodypartsRecord.class;
    }

    /**
     * The column <code>public.bodyparts.name</code>.
     */
    public final TableField<BodypartsRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.bodyparts.description</code>.
     */
    public final TableField<BodypartsRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.bodyparts</code> table reference
     */
    public Bodyparts() {
        this(DSL.name("bodyparts"), null);
    }

    /**
     * Create an aliased <code>public.bodyparts</code> table reference
     */
    public Bodyparts(String alias) {
        this(DSL.name(alias), BODYPARTS);
    }

    /**
     * Create an aliased <code>public.bodyparts</code> table reference
     */
    public Bodyparts(Name alias) {
        this(alias, BODYPARTS);
    }

    private Bodyparts(Name alias, Table<BodypartsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Bodyparts(Name alias, Table<BodypartsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Bodyparts(Table<O> child, ForeignKey<O, BodypartsRecord> key) {
        super(child, key, BODYPARTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<BodypartsRecord> getPrimaryKey() {
        return Keys.BODYPARTS_PKEY;
    }

    @Override
    public List<UniqueKey<BodypartsRecord>> getKeys() {
        return Arrays.<UniqueKey<BodypartsRecord>>asList(Keys.BODYPARTS_PKEY);
    }

    @Override
    public Bodyparts as(String alias) {
        return new Bodyparts(DSL.name(alias), this);
    }

    @Override
    public Bodyparts as(Name alias) {
        return new Bodyparts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Bodyparts rename(String name) {
        return new Bodyparts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Bodyparts rename(Name name) {
        return new Bodyparts(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
