/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database.tables;


import de.uke.iam.parkinson_on_fhir.database.Keys;
import de.uke.iam.parkinson_on_fhir.database.Public;
import de.uke.iam.parkinson_on_fhir.database.tables.records.SubjectsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Subjects extends TableImpl<SubjectsRecord> {

    private static final long serialVersionUID = 1213424970;

    /**
     * The reference instance of <code>public.subjects</code>
     */
    public static final Subjects SUBJECTS = new Subjects();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SubjectsRecord> getRecordType() {
        return SubjectsRecord.class;
    }

    /**
     * The column <code>public.subjects.subject_id</code>.
     */
    public final TableField<SubjectsRecord, Integer> SUBJECT_ID = createField(DSL.name("subject_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.subjects.source</code>.
     */
    public final TableField<SubjectsRecord, Integer> SOURCE = createField(DSL.name("source"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.subjects.description</code>.
     */
    public final TableField<SubjectsRecord, String> DESCRIPTION = createField(DSL.name("description"), org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.subjects</code> table reference
     */
    public Subjects() {
        this(DSL.name("subjects"), null);
    }

    /**
     * Create an aliased <code>public.subjects</code> table reference
     */
    public Subjects(String alias) {
        this(DSL.name(alias), SUBJECTS);
    }

    /**
     * Create an aliased <code>public.subjects</code> table reference
     */
    public Subjects(Name alias) {
        this(alias, SUBJECTS);
    }

    private Subjects(Name alias, Table<SubjectsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Subjects(Name alias, Table<SubjectsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Subjects(Table<O> child, ForeignKey<O, SubjectsRecord> key) {
        super(child, key, SUBJECTS);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public Identity<SubjectsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SUBJECTS;
    }

    @Override
    public UniqueKey<SubjectsRecord> getPrimaryKey() {
        return Keys.SUBJECTS_PKEY;
    }

    @Override
    public List<UniqueKey<SubjectsRecord>> getKeys() {
        return Arrays.<UniqueKey<SubjectsRecord>>asList(Keys.SUBJECTS_PKEY);
    }

    @Override
    public List<ForeignKey<SubjectsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SubjectsRecord, ?>>asList(Keys.SUBJECTS__SOURCE_FK);
    }

    public Sources sources() {
        return new Sources(this, Keys.SUBJECTS__SOURCE_FK);
    }

    @Override
    public Subjects as(String alias) {
        return new Subjects(DSL.name(alias), this);
    }

    @Override
    public Subjects as(Name alias) {
        return new Subjects(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Subjects rename(String name) {
        return new Subjects(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Subjects rename(Name name) {
        return new Subjects(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
