/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database.tables.records;


import de.uke.iam.parkinson_on_fhir.database.tables.Bodyparts;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BodypartsRecord extends UpdatableRecordImpl<BodypartsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -941630183;

    /**
     * Setter for <code>public.bodyparts.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.bodyparts.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.bodyparts.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.bodyparts.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Bodyparts.BODYPARTS.NAME;
    }

    @Override
    public Field<String> field2() {
        return Bodyparts.BODYPARTS.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getName();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getName();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public BodypartsRecord value1(String value) {
        setName(value);
        return this;
    }

    @Override
    public BodypartsRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public BodypartsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BodypartsRecord
     */
    public BodypartsRecord() {
        super(Bodyparts.BODYPARTS);
    }

    /**
     * Create a detached, initialised BodypartsRecord
     */
    public BodypartsRecord(String name, String description) {
        super(Bodyparts.BODYPARTS);

        set(0, name);
        set(1, description);
    }
}
