/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database.tables.records;


import de.uke.iam.parkinson_on_fhir.database.tables.Devices;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DevicesRecord extends UpdatableRecordImpl<DevicesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -419077187;

    /**
     * Setter for <code>public.devices.device</code>.
     */
    public void setDevice(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.devices.device</code>.
     */
    public String getDevice() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.devices.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.devices.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Devices.DEVICES.DEVICE;
    }

    @Override
    public Field<String> field2() {
        return Devices.DEVICES.DESCRIPTION;
    }

    @Override
    public String component1() {
        return getDevice();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String value1() {
        return getDevice();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public DevicesRecord value1(String value) {
        setDevice(value);
        return this;
    }

    @Override
    public DevicesRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DevicesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevicesRecord
     */
    public DevicesRecord() {
        super(Devices.DEVICES);
    }

    /**
     * Create a detached, initialised DevicesRecord
     */
    public DevicesRecord(String device, String description) {
        super(Devices.DEVICES);

        set(0, device);
        set(1, description);
    }
}
