/*
 * This file is generated by jOOQ.
 */
package de.uke.iam.parkinson_on_fhir.database.tables.records;


import de.uke.iam.parkinson_on_fhir.database.tables.Sources;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourcesRecord extends UpdatableRecordImpl<SourcesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -701940367;

    /**
     * Setter for <code>public.sources.source_id</code>.
     */
    public void setSourceId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sources.source_id</code>.
     */
    public Integer getSourceId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sources.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sources.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Sources.SOURCES.SOURCE_ID;
    }

    @Override
    public Field<String> field2() {
        return Sources.SOURCES.DESCRIPTION;
    }

    @Override
    public Integer component1() {
        return getSourceId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Integer value1() {
        return getSourceId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public SourcesRecord value1(Integer value) {
        setSourceId(value);
        return this;
    }

    @Override
    public SourcesRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SourcesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourcesRecord
     */
    public SourcesRecord() {
        super(Sources.SOURCES);
    }

    /**
     * Create a detached, initialised SourcesRecord
     */
    public SourcesRecord(Integer sourceId, String description) {
        super(Sources.SOURCES);

        set(0, sourceId);
        set(1, description);
    }
}
